service: javascript-template-sls

licenseKey: ${ssm:/aws/reference/secretsmanager/serverless-framework-access-key}

provider:
  deploymentBucket:
    name: com.reference-architecture.deploys
  environment:
    POWERTOOLS_LOGGER_SAMPLE_RATE: 1
  logRetentionInDays: 7
  name: aws
  runtime: nodejs24.x

functions:
  hello:
    handler: src/helloWorld
    events:
      - httpApi:
          method: get
          path: /hello

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false

plugins:
  - serverless-deployment-bucket

package:
  individually: true
